# Generated by Django 6.1 on 2026-08-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0022_personalaccount_cover_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_professionals', to='jobs.jobcategory')),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interests', to='identity.professionalaccount')),
            ],
            options={
                'ordering': ['job_category__display_order', 'job_category__name'],
                'constraints': [models.UniqueConstraint(fields=('professional_account', 'job_category'), name='unique_professional_job_interest')],
            },
        ),
    ]
