# Generated by Django 6.1 on 2026-08-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_personalaccount'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-Owner'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('employee', 'Employee / Staff'), ('member', 'Member')], max_length=30)),
                ('membership_status', models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_relationships', to='identity.useridentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='organization.organization')),
            ],
            options={
                'ordering': ['organization', 'relationship_type'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'identity'), name='unique_organization_identity_relationship')],
            },
        ),
    ]
