# Generated by Django 6.1 on 2026-08-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_personalaccount'),
        ('organization', '0002_organizationrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-Owner'), ('super_admin', 'Super Admin'), ('co_super_admin', 'Co-Super Admin'), ('global_department_admin', 'Global Department Admin'), ('co_global_department_admin', 'Co-Global Department Admin'), ('regional_admin', 'Regional Admin'), ('co_regional_admin', 'Co-Regional Admin'), ('country_admin', 'Country Admin'), ('co_country_admin', 'Co-Country Admin'), ('country_department_admin', 'Country Department Admin'), ('co_country_department_admin', 'Co-Country Department Admin'), ('staff', 'Staff')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_roles', to='identity.useridentity')),
            ],
            options={
                'ordering': ['role_type'],
            },
        ),
    ]
