# Generated by Django 6.1 on 2026-09-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_key', models.CharField(max_length=150, unique=True)),
                ('feature_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='premium', max_length=20)),
                ('trial_enabled', models.BooleanField(default=False)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'feature_name'],
            },
        ),
    ]
