# Generated by Django 6.1 on 2026-09-13 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpremiumsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('method_type', models.CharField(choices=[('manual', 'Manual Payment'), ('gateway', 'Payment Gateway')], default='manual', max_length=20)),
                ('provider_key', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('transaction_id', models.CharField(max_length=150, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('sender_account', models.CharField(blank=True, max_length=100)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='core.premiumpackage')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('textarea', 'Long Text'), ('url', 'URL')], default='text', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.paymentmethod')),
            ],
            options={
                'ordering': ['display_order', 'field_label'],
                'constraints': [models.UniqueConstraint(fields=('payment_method', 'field_key'), name='unique_payment_method_field_key')],
            },
        ),
    ]
