# Generated by Django 6.1 on 2026-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentmethod_paymenttransaction_paymentmethodfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
