# Generated by Django 6.1 on 2026-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymenttransaction_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodfield',
            name='is_customer_input',
            field=models.BooleanField(default=False),
        ),
    ]
