# Generated by Django 6.1 on 2026-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paymentmethodfield_is_customer_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_type',
            field=models.CharField(choices=[('manual', 'Manual Approval'), ('automatic', 'Automatic Verification')], default='manual', max_length=20),
        ),
    ]
