# Generated by Django 6.1 on 2026-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paymentmethod_verification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureaccesscontrol',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('company', 'Company')], default='personal', max_length=20),
        ),
    ]
