# Generated by Django 6.1 on 2026-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_featureaccesscontrol_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFontStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font_key', models.CharField(max_length=100, unique=True)),
                ('font_name', models.CharField(max_length=150)),
                ('font_family', models.CharField(max_length=255)),
                ('category', models.CharField(default='Standard', max_length=50)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'font_name'],
            },
        ),
    ]
