# Generated by Django 6.1 on 2026-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_personalfontstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccesscontrol',
            name='feature_key',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='featureaccesscontrol',
            constraint=models.UniqueConstraint(fields=('feature_key', 'account_type'), name='unique_feature_per_account_type'),
        ),
    ]
