# Generated by Django 6.1 on 2026-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_featureaccesscontrol_feature_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfontstyle',
            name='font_source',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='personalfontstyle',
            name='font_weights',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalfontstyle',
            name='language_support',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
