# Generated by Django 6.1 on 2026-09-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_personalfontstyle_font_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfontstyle',
            name='local_font_file',
            field=models.FileField(blank=True, null=True, upload_to='personal_fonts/'),
        ),
    ]
