# Generated by Django 6.1 on 2026-09-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_personalfontstyle_local_font_file'),
        ('identity', '0033_socialmediaplatform_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFontFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='core.personalfontstyle')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_fonts', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('personal_account', 'font'), name='unique_user_font_favorite')],
            },
        ),
    ]
