# Generated by Django 6.1 on 2026-09-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userfontfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColleagueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('allow_user_remove', models.BooleanField(default=False)),
                ('allow_status_change', models.BooleanField(default=True)),
                ('require_mutual_confirmation', models.BooleanField(default=True)),
                ('running_status_enabled', models.BooleanField(default=True)),
                ('previous_status_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colleague Setting',
                'verbose_name_plural': 'Colleague Settings',
            },
        ),
    ]
