# Generated by Django 6.1 on 2026-09-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_default_colleague_setting'),
        ('organization', '0009_country_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralPopupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('popup_id', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('custom', 'Custom'), ('fullscreen', 'Fullscreen')], default='medium', max_length=20)),
                ('position', models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('height', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='popup_settings', to='organization.country')),
            ],
            options={
                'ordering': ['country__name', 'popup_id'],
                'constraints': [models.UniqueConstraint(fields=('popup_id', 'country'), name='unique_popup_per_country')],
            },
        ),
    ]
