# Generated by Django 6.1 on 2026-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_centralpopupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='auto_close_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='auto_close_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='backdrop_blur',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='backdrop_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='backdrop_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='backdrop_opacity',
            field=models.PositiveSmallIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='popup/backgrounds/'),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='background_opacity',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='border',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='border_radius',
            field=models.CharField(default='18px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='box_shadow',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='close_on_escape',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='close_on_outside_click',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='show_close_button',
            field=models.BooleanField(default=True),
        ),
    ]
