# Generated by Django 6.1 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_centralpopupsetting_auto_close_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='body_color',
            field=models.CharField(default='#374151', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='body_font_size',
            field=models.CharField(default='16px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='body_font_weight',
            field=models.CharField(default='400', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_background_color',
            field=models.CharField(default='#0A66C2', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_border',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_border_radius',
            field=models.CharField(default='8px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_font_size',
            field=models.CharField(default='14px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_font_weight',
            field=models.CharField(default='500', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_padding',
            field=models.CharField(default='10px 18px', max_length=50),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_border',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_height',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='letter_spacing',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='line_height',
            field=models.CharField(default='1.5', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='title_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='title_font_size',
            field=models.CharField(default='20px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='title_font_weight',
            field=models.CharField(default='600', max_length=30),
        ),
    ]
