# Generated by Django 6.1 on 2026-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_centralpopupsetting_body_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='animation',
            field=models.CharField(choices=[('fade', 'Fade'), ('scale', 'Scale'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('none', 'None')], default='scale', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='animation_duration',
            field=models.PositiveIntegerField(default=220),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_border_radius',
            field=models.CharField(default='18px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_bottom_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_padding',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='bottom', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='mobile_width',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
