# Generated by Django 6.1 on 2026-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_centralpopupsetting_animation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralPopupRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('popup_id', models.CharField(max_length=100, unique=True)),
                ('popup_name', models.CharField(max_length=255)),
                ('popup_type', models.CharField(choices=[('special_day', 'Special Day'), ('iconic_person', 'Iconic Person'), ('memorial', 'Memorial / Tribute'), ('national_event', 'National Event'), ('announcement', 'Announcement'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'popup_name'],
            },
        ),
    ]
