# Generated by Django 6.1 on 2026-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_centralpopupregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralpopupsetting',
            options={'ordering': ['country__name', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='centralpopupsetting',
            name='unique_popup_per_country',
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='popups',
            field=models.ManyToManyField(blank=True, related_name='settings', to='core.centralpopupregistry'),
        ),
        migrations.RemoveField(
            model_name='centralpopupsetting',
            name='popup_id',
        ),
    ]
