# Generated by Django 6.1 on 2026-09-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_centralpopupsetting_all_popups'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='button_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='content_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='content_subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='content_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='display_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='display_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='repeat_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
