# Generated by Django 6.1 on 2026-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_centralpopupsetting_button_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='background_visual_priority',
            field=models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=10),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='body_link_color',
            field=models.CharField(default='#0A66C2', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='body_secondary_color',
            field=models.CharField(default='#6B7280', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_background_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_color',
            field=models.CharField(default='#6B7280', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_font_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_font_size',
            field=models.CharField(default='16px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_font_weight',
            field=models.CharField(default='400', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_letter_spacing',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_subtitle_line_height',
            field=models.CharField(default='1.5', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_font_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_font_size',
            field=models.CharField(default='28px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_font_weight',
            field=models.CharField(default='700', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_letter_spacing',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='header_title_line_height',
            field=models.CharField(default='1.2', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_active_background_color',
            field=models.CharField(default='#0A66C2', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_active_font_weight',
            field=models.CharField(default='600', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_active_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_background_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_border_color',
            field=models.CharField(default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_font_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_font_size',
            field=models.CharField(default='14px', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_font_weight',
            field=models.CharField(default='500', max_length=30),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_text_color',
            field=models.CharField(default='#374151', max_length=20),
        ),
    ]
