# Generated by Django 6.1 on 2026-09-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_centralpopupsetting_background_visual_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='border_color',
            field=models.CharField(blank=True, default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='border_style',
            field=models.CharField(choices=[('none', 'None'), ('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted'), ('double', 'Double')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='border_width',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
