# Generated by Django 6.1 on 2026-09-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_centralpopupsetting_border_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralpopupsetting',
            name='backdrop_blur',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='centralpopupsetting',
            name='button_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='centralpopupsetting',
            name='button_border',
            field=models.CharField(blank=True, default='1px solid #0A66C2', max_length=100),
        ),
        migrations.AlterField(
            model_name='centralpopupsetting',
            name='button_font_weight',
            field=models.CharField(default='600', max_length=30),
        ),
    ]
