# Generated by Django 6.1 on 2026-09-20 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_centralpopupsetting_backdrop_blur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('company', 'Company')], max_length=20)),
                ('background_color', models.CharField(default='#f8fbff', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='messaging_backgrounds/')),
                ('background_visual_priority', models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', max_length=10)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_appearances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_type'],
                'constraints': [models.UniqueConstraint(fields=('identity', 'account_type'), name='unique_messaging_appearance_per_account')],
            },
        ),
    ]
