# Generated by Django 6.1 on 2026-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_messagingappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingappearance',
            name='tab_color',
            field=models.CharField(default='#0a66c2', max_length=20),
        ),
        migrations.AddField(
            model_name='messagingappearance',
            name='tab_color_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
