# Generated by Django 6.1 on 2026-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_centralpopupsetting_tab_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralpopupsetting',
            name='messaging_font_family',
            field=models.CharField(default='Arial', max_length=255),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_color',
            field=models.CharField(default='#0a66c2', max_length=20),
        ),
        migrations.AddField(
            model_name='centralpopupsetting',
            name='tab_color_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
