# Generated by Django 6.1 on 2026-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_centralpopupsetting_messaging_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralpopupsetting',
            name='messaging_font_family',
        ),
        migrations.RemoveField(
            model_name='centralpopupsetting',
            name='tab_color',
        ),
        migrations.RemoveField(
            model_name='centralpopupsetting',
            name='tab_color_enabled',
        ),
        migrations.AddField(
            model_name='messagingappearance',
            name='messaging_font_family',
            field=models.CharField(default='Arial', max_length=255),
        ),
    ]
