# Generated by Django 6.1 on 2026-09-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dmail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmail',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='dmail',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='dmail',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_dmail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DmailMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('draft', 'Draft'), ('starred', 'Starred'), ('important', 'Important'), ('archived', 'Archived'), ('trash', 'Trash')], default='inbox', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('dmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='core.dmail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmail_mailboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('dmail', 'user'), name='unique_dmail_mailbox_per_user')],
            },
        ),
    ]
