# Generated by Django 6.1 on 2026-09-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_dmail_folder_remove_dmail_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.dmail'),
        ),
        migrations.AddField(
            model_name='dmail',
            name='thread_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
