# Generated by Django 6.1 on 2026-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccesscontrol',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('company', 'Company'), ('institution', 'Institution')], default='personal', max_length=20),
        ),
    ]
