# Generated by Django 6.1 on 2026-09-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_featureaccesscontrol_account_type'),
        ('organization', '0011_alter_region_options_region_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('native_name', models.CharField(blank=True, max_length=150)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('conversion_method', models.CharField(choices=[('gregorian', 'Gregorian'), ('calculated', 'Calculated'), ('moon_sighting', 'Local Moon Sighting'), ('umm_al_qura', 'Umm al-Qura'), ('regional', 'Regional')], default='calculated', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('allow_favorite', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_settings', to='core.calendar')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_settings', to='organization.country')),
            ],
            options={
                'ordering': ['country__name', 'calendar__display_order'],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'country'), name='unique_calendar_country')],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='core.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'calendar'), name='unique_user_calendar_favorite')],
            },
        ),
    ]
