from django.core.management.base import BaseCommand

from institution.models import Subject


SUBJECTS = [
    # School - General
    ("Bangla 1st Paper", "BAN101"),
    ("Bangla 2nd Paper", "BAN102"),
    ("English 1st Paper", "ENG101"),
    ("English 2nd Paper", "ENG102"),
    ("General Mathematics", "MAT101"),
    ("Higher Mathematics", "MAT102"),
    ("General Science", "SCI101"),
    ("Social Science", "SOC101"),
    ("Civics and Citizenship", "CIV101"),
    ("Geography and Environment", "GEO101"),
    ("History of Bangladesh", "HIS101"),
    ("History and Social Science", "HIS102"),
    ("Religion and Moral Education", "REL101"),
    ("Physical Education", "PED101"),
    ("Agriculture Studies", "AGR101"),
    ("Home Science", "HSC101"),
    ("Career Education", "CAR101"),
    ("Digital Technology", "DIG101"),
    ("Information and Communication Technology", "ICT101"),

    # Science
    ("Physics 1st Paper", "PHY101"),
    ("Physics 2nd Paper", "PHY102"),
    ("Chemistry 1st Paper", "CHE101"),
    ("Chemistry 2nd Paper", "CHE102"),
    ("Biology 1st Paper", "BIO101"),
    ("Biology 2nd Paper", "BIO102"),
    ("Higher Mathematics 1st Paper", "MAT201"),
    ("Higher Mathematics 2nd Paper", "MAT202"),
    ("Statistics", "STA101"),
    ("Environmental Science", "ENV101"),
    ("Earth Science", "EAR101"),
    ("Astronomy", "AST101"),
    ("Applied Physics", "APH101"),
    ("Applied Chemistry", "ACH101"),
    ("Biochemistry", "BIOC101"),
    ("Microbiology", "MIC101"),
    ("Biotechnology", "BIT101"),
    ("Genetics", "GEN101"),
    ("Molecular Biology", "MOL101"),
    ("Botany", "BOT101"),
    ("Zoology", "ZOO101"),

    # Mathematics
    ("Algebra", "ALG101"),
    ("Geometry", "GEO201"),
    ("Trigonometry", "TRI101"),
    ("Calculus", "CAL101"),
    ("Differential Calculus", "CAL102"),
    ("Integral Calculus", "CAL103"),
    ("Differential Equations", "DEQ101"),
    ("Linear Algebra", "LAL101"),
    ("Discrete Mathematics", "DMT101"),
    ("Number Theory", "NUM101"),
    ("Probability", "PRO101"),
    ("Mathematical Statistics", "MST101"),
    ("Numerical Analysis", "NAN101"),
    ("Operations Research", "OR101"),
    ("Real Analysis", "RA101"),
    ("Complex Analysis", "CA101"),
    ("Abstract Algebra", "AAL101"),

    # Computer Science / IT
    ("Computer Fundamentals", "CSE101"),
    ("Programming Fundamentals", "CSE102"),
    ("Object Oriented Programming", "CSE103"),
    ("Data Structures", "CSE104"),
    ("Algorithms", "CSE105"),
    ("Database Management Systems", "CSE106"),
    ("Operating Systems", "CSE107"),
    ("Computer Networks", "CSE108"),
    ("Computer Architecture", "CSE109"),
    ("Digital Logic Design", "CSE110"),
    ("Software Engineering", "CSE111"),
    ("Web Development", "CSE112"),
    ("Mobile Application Development", "CSE113"),
    ("Artificial Intelligence", "CSE114"),
    ("Machine Learning", "CSE115"),
    ("Deep Learning", "CSE116"),
    ("Data Science", "CSE117"),
    ("Big Data", "CSE118"),
    ("Cloud Computing", "CSE119"),
    ("Cyber Security", "CSE120"),
    ("Cryptography", "CSE121"),
    ("Computer Graphics", "CSE122"),
    ("Computer Vision", "CSE123"),
    ("Natural Language Processing", "CSE124"),
    ("Distributed Systems", "CSE125"),
    ("Parallel Computing", "CSE126"),
    ("Compiler Design", "CSE127"),
    ("Embedded Systems", "CSE128"),
    ("Internet of Things", "CSE129"),
    ("Blockchain Technology", "CSE130"),
    ("Information Security", "CSE131"),
    ("Digital Forensics", "CSE132"),
    ("Human Computer Interaction", "CSE133"),
    ("Software Testing", "CSE134"),
    ("DevOps", "CSE135"),
    ("Computer Organization", "CSE136"),
    ("Information Systems", "CSE137"),
    ("Management Information Systems", "CSE138"),

    # Business
    ("Principles of Accounting", "ACC101"),
    ("Financial Accounting", "ACC102"),
    ("Cost Accounting", "ACC103"),
    ("Management Accounting", "ACC104"),
    ("Auditing", "ACC105"),
    ("Taxation", "ACC106"),
    ("Corporate Finance", "FIN101"),
    ("Financial Management", "FIN102"),
    ("Investment Management", "FIN103"),
    ("Banking", "FIN104"),
    ("Insurance", "FIN105"),
    ("Principles of Marketing", "MKT101"),
    ("Marketing Management", "MKT102"),
    ("Consumer Behavior", "MKT103"),
    ("Digital Marketing", "MKT104"),
    ("Brand Management", "MKT105"),
    ("Sales Management", "MKT106"),
    ("Human Resource Management", "HRM101"),
    ("Organizational Behavior", "HRM102"),
    ("Recruitment and Selection", "HRM103"),
    ("Training and Development", "HRM104"),
    ("Operations Management", "MGT101"),
    ("Strategic Management", "MGT102"),
    ("Project Management", "MGT103"),
    ("Supply Chain Management", "SCM101"),
    ("Business Communication", "BUS101"),
    ("Business Law", "BUS102"),
    ("Business Ethics", "BUS103"),
    ("Entrepreneurship", "ENT101"),
    ("Business Analytics", "BUS104"),
    ("International Business", "BUS105"),
    ("E-Commerce", "BUS106"),

    # Economics / Social Science
    ("Principles of Economics", "ECO101"),
    ("Microeconomics", "ECO102"),
    ("Macroeconomics", "ECO103"),
    ("Development Economics", "ECO104"),
    ("International Economics", "ECO105"),
    ("Public Finance", "ECO106"),
    ("Econometrics", "ECO107"),
    ("Economic History", "ECO108"),
    ("Political Science", "POL101"),
    ("Public Administration", "PAD101"),
    ("International Relations", "IR101"),
    ("Sociology", "SOC102"),
    ("Social Work", "SW101"),
    ("Anthropology", "ANT101"),
    ("Criminology", "CRM101"),
    ("Development Studies", "DEV101"),
    ("Gender Studies", "GEN101"),
    ("Population Studies", "POP101"),
    ("Social Research Methods", "SRM101"),
    ("Political Theory", "POL102"),
    ("Comparative Politics", "POL103"),
    ("Public Policy", "POL104"),
    ("Governance Studies", "GOV101"),

    # Humanities / Languages
    ("Bangla Literature", "BAN201"),
    ("Bangla Language", "BAN202"),
    ("English Literature", "ENG201"),
    ("English Language", "ENG202"),
    ("English Grammar", "ENG203"),
    ("English Composition", "ENG204"),
    ("Linguistics", "LIN101"),
    ("Applied Linguistics", "LIN102"),
    ("Translation Studies", "TRA101"),
    ("History", "HIS201"),
    ("Ancient History", "HIS202"),
    ("Medieval History", "HIS203"),
    ("Modern History", "HIS204"),
    ("World History", "HIS205"),
    ("Philosophy", "PHI101"),
    ("Logic", "PHI102"),
    ("Ethics", "PHI103"),
    ("Islamic Studies", "ISL101"),
    ("Islamic History", "ISL102"),
    ("Islamic Theology", "ISL103"),
    ("Quran Studies", "ISL104"),
    ("Hadith Studies", "ISL105"),
    ("Fiqh", "ISL106"),
    ("Arabic Language", "ARB101"),
    ("Arabic Literature", "ARB102"),
    ("Persian Language", "PER101"),
    ("Urdu Language", "URD101"),
    ("Sanskrit", "SAN101"),

    # Engineering
    ("Engineering Mathematics", "ENGM101"),
    ("Engineering Physics", "ENGP101"),
    ("Engineering Chemistry", "ENGC101"),
    ("Engineering Drawing", "ENGD101"),
    ("Engineering Mechanics", "ENGM102"),
    ("Fluid Mechanics", "ENGM103"),
    ("Thermodynamics", "ENGM104"),
    ("Heat Transfer", "ENGM105"),
    ("Strength of Materials", "ENGM106"),
    ("Machine Design", "ENGM107"),
    ("Manufacturing Processes", "ENGM108"),
    ("Electrical Circuits", "EEE101"),
    ("Electronic Devices", "EEE102"),
    ("Power Systems", "EEE103"),
    ("Electrical Machines", "EEE104"),
    ("Control Systems", "EEE105"),
    ("Digital Electronics", "EEE106"),
    ("Analog Electronics", "EEE107"),
    ("Communication Systems", "EEE108"),
    ("Microprocessors", "EEE109"),
    ("Signals and Systems", "EEE110"),
    ("Structural Analysis", "CE101"),
    ("Concrete Technology", "CE102"),
    ("Geotechnical Engineering", "CE103"),
    ("Transportation Engineering", "CE104"),
    ("Water Resources Engineering", "CE105"),
    ("Surveying", "CE106"),
    ("Environmental Engineering", "CE107"),
    ("Construction Management", "CE108"),
    ("Machine Tools", "ME101"),
    ("Automobile Engineering", "ME102"),
    ("Production Engineering", "ME103"),
    ("Industrial Engineering", "ME104"),
    ("Mechatronics", "ME105"),
    ("Robotics", "ME106"),
    ("Textile Engineering", "TE101"),
    ("Textile Technology", "TE102"),
    ("Textile Chemistry", "TE103"),
    ("Yarn Manufacturing", "TE104"),
    ("Fabric Manufacturing", "TE105"),
    ("Apparel Manufacturing", "TE106"),
    ("Apparel Merchandising", "TE107"),

    # Medical
    ("Anatomy", "MED101"),
    ("Physiology", "MED102"),
    ("Biochemistry", "MED103"),
    ("Pharmacology", "MED104"),
    ("Pathology", "MED105"),
    ("Microbiology", "MED106"),
    ("Community Medicine", "MED107"),
    ("Forensic Medicine", "MED108"),
    ("Medicine", "MED109"),
    ("Surgery", "MED110"),
    ("Paediatrics", "MED111"),
    ("Obstetrics and Gynaecology", "MED112"),
    ("Cardiology", "MED113"),
    ("Neurology", "MED114"),
    ("Dermatology", "MED115"),
    ("Psychiatry", "MED116"),
    ("Orthopaedics", "MED117"),
    ("Ophthalmology", "MED118"),
    ("Otolaryngology", "MED119"),
    ("Radiology", "MED120"),
    ("Anesthesiology", "MED121"),
    ("Oncology", "MED122"),
    ("Nephrology", "MED123"),
    ("Gastroenterology", "MED124"),
    ("Endocrinology", "MED125"),
    ("Urology", "MED126"),
    ("Emergency Medicine", "MED127"),
    ("Public Health", "MED128"),
    ("Epidemiology", "MED129"),

    # Nursing / Allied Health
    ("Fundamentals of Nursing", "NUR101"),
    ("Medical Surgical Nursing", "NUR102"),
    ("Community Health Nursing", "NUR103"),
    ("Child Health Nursing", "NUR104"),
    ("Maternal Health Nursing", "NUR105"),
    ("Mental Health Nursing", "NUR106"),
    ("Nursing Research", "NUR107"),
    ("Nursing Management", "NUR108"),
    ("Midwifery", "MID101"),
    ("Pharmacy Practice", "PHA101"),
    ("Pharmacognosy", "PHA102"),
    ("Pharmaceutics", "PHA103"),
    ("Pharmaceutical Chemistry", "PHA104"),
    ("Clinical Pharmacy", "PHA105"),
    ("Physiotherapy", "PT101"),
    ("Occupational Therapy", "OT101"),
    ("Medical Laboratory Science", "MLS101"),
    ("Medical Imaging", "IMG101"),
    ("Radiography", "RAD101"),
    ("Optometry", "OPT101"),
    ("Audiology", "AUD101"),
    ("Nutrition and Dietetics", "NUT101"),

    # Agriculture
    ("Agronomy", "AGR101"),
    ("Soil Science", "AGR102"),
    ("Horticulture", "AGR103"),
    ("Plant Pathology", "AGR104"),
    ("Entomology", "AGR105"),
    ("Agricultural Economics", "AGR106"),
    ("Agricultural Extension", "AGR107"),
    ("Agricultural Engineering", "AGR108"),
    ("Animal Science", "AGR109"),
    ("Animal Nutrition", "AGR110"),
    ("Fisheries", "AGR111"),
    ("Veterinary Science", "AGR112"),
    ("Crop Science", "AGR113"),
    ("Plant Breeding", "AGR114"),
    ("Genetics", "AGR115"),
    ("Food Science", "AGR116"),
    ("Food Technology", "AGR117"),
    ("Dairy Science", "AGR118"),

    # Law
    ("Constitutional Law", "LAW101"),
    ("Criminal Law", "LAW102"),
    ("Civil Law", "LAW103"),
    ("Contract Law", "LAW104"),
    ("Company Law", "LAW105"),
    ("Commercial Law", "LAW106"),
    ("International Law", "LAW107"),
    ("Human Rights Law", "LAW108"),
    ("Family Law", "LAW109"),
    ("Labour Law", "LAW110"),
    ("Environmental Law", "LAW111"),
    ("Intellectual Property Law", "LAW112"),
    ("Cyber Law", "LAW113"),
    ("Tax Law", "LAW114"),
    ("Legal Research", "LAW115"),

    # Arts / Media
    ("Fine Arts", "ART101"),
    ("Drawing", "ART102"),
    ("Painting", "ART103"),
    ("Sculpture", "ART104"),
    ("Graphic Design", "ART105"),
    ("Photography", "ART106"),
    ("Music", "ART107"),
    ("Vocal Music", "ART108"),
    ("Instrumental Music", "ART109"),
    ("Theatre", "ART110"),
    ("Drama", "ART111"),
    ("Film Studies", "ART112"),
    ("Mass Communication", "ART113"),
    ("Journalism", "ART114"),
    ("Broadcast Journalism", "ART115"),
    ("Digital Media", "ART116"),
    ("Advertising", "ART117"),
    ("Public Relations", "ART118"),

    # Tourism / Hospitality
    ("Tourism Management", "TOU101"),
    ("Hospitality Management", "TOU102"),
    ("Hotel Management", "TOU103"),
    ("Travel Management", "TOU104"),
    ("Culinary Arts", "TOU105"),
    ("Food and Beverage Management", "TOU106"),
    ("Event Management", "TOU107"),
    ("Aviation Management", "TOU108"),

    # Technical / Vocational
    ("Technical Drawing", "TV101"),
    ("Electrical Technology", "TV102"),
    ("Electronics Technology", "TV103"),
    ("Mechanical Technology", "TV104"),
    ("Civil Technology", "TV105"),
    ("Computer Technology", "TV106"),
    ("Automobile Technology", "TV107"),
    ("Power Technology", "TV108"),
    ("Refrigeration and Air Conditioning", "TV109"),
    ("Garments Technology", "TV110"),
    ("Welding Technology", "TV111"),
    ("Machine Tools Technology", "TV112"),
    ("Food Technology", "TV113"),
    ("Architecture Technology", "TV114"),
]


class Command(BaseCommand):
    help = "Seed global Deepafy subjects."

    def handle(self, *args, **options):
        created = 0
        skipped = 0

        for name, code in SUBJECTS:
            existing = Subject.objects.filter(name__iexact=name).first()

            if existing:
                skipped += 1
                continue

            Subject.objects.create(
                name=name,
                code=code,
                is_active=True,
            )
            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Created: {created} | "
                f"Skipped existing: {skipped} | "
                f"Total: {Subject.objects.count()}"
            )
        )
