from django.core.management.base import BaseCommand
from institution.models import Department


DEPARTMENTS = [
    # Education
    ("Education", "EDU"),
    ("Educational Administration", "EADM"),
    ("Educational Psychology", "EPSY"),
    ("Curriculum and Instruction", "CIN"),
    ("Special Education", "SPED"),
    ("Early Childhood Education", "ECE"),
    ("Primary Education", "PEDU"),
    ("Secondary Education", "SEDU"),
    ("Higher Education", "HEDU"),
    ("Vocational Education", "VE"),
    ("Teacher Education", "TEDU"),

    # Computer & IT
    ("Computer Science", "CSE"),
    ("Computer Engineering", "CEN"),
    ("Information Technology", "IT"),
    ("Information and Communication Technology", "ICT"),
    ("Software Engineering", "SE"),
    ("Information Systems", "IS"),
    ("Management Information Systems", "MIS"),
    ("Computer Applications", "CA"),
    ("Computer Networks", "CN"),
    ("Cloud Computing", "CC"),
    ("Web Technology", "WEB"),
    ("Mobile Application Development", "MAD"),
    ("Artificial Intelligence", "AI"),
    ("Machine Learning", "ML"),
    ("Data Science", "DSC"),
    ("Statistics and Data Science", "SDS"),
    ("Big Data Analytics", "BDA"),
    ("Cyber Security", "CYB"),
    ("Information Security", "INFOSEC"),
    ("Digital Forensics", "DF"),
    ("Blockchain Technology", "BCT"),
    ("Internet of Things", "IOT"),
    ("Robotics Engineering", "ROB"),
    ("Computer Graphics and Multimedia", "CGM"),
    ("Game Development", "GD"),
    ("Human Computer Interaction", "HCI"),
    ("Computational Science", "CSCI"),
    ("Natural Language Processing", "NLP"),
    ("Computer Vision", "CV"),

    # Engineering
    ("Civil Engineering", "CE"),
    ("Electrical Engineering", "EEE"),
    ("Electronics Engineering", "ECE"),
    ("Mechanical Engineering", "ME"),
    ("Industrial Engineering", "IE"),
    ("Industrial and Production Engineering", "IPE"),
    ("Chemical Engineering", "CHEE"),
    ("Biomedical Engineering", "BME"),
    ("Environmental Engineering", "ENVENG"),
    ("Textile Engineering", "TE"),
    ("Telecommunication Engineering", "TEL"),
    ("Communication Engineering", "COMM"),
    ("Aeronautical Engineering", "AERO"),
    ("Aerospace Engineering", "AER"),
    ("Automotive Engineering", "AUTO"),
    ("Marine Engineering", "MAR"),
    ("Mining Engineering", "MIN"),
    ("Petroleum Engineering", "PET"),
    ("Nuclear Engineering", "NUC"),
    ("Power Engineering", "POWER"),
    ("Renewable Energy Engineering", "REE"),
    ("Structural Engineering", "STRUCT"),
    ("Transportation Engineering", "TRANS"),
    ("Water Resources Engineering", "WRE"),
    ("Construction Engineering", "CON"),
    ("Control Engineering", "CTRL"),
    ("Instrumentation Engineering", "INS"),
    ("Mechatronics Engineering", "MTE"),
    ("Materials Science and Engineering", "MSE"),
    ("Robotics Engineering", "ROB"),
    ("Agricultural Engineering", "AE"),
    ("Fire Safety Engineering", "FSE"),
    ("Railway Engineering", "RAIL"),
    ("Urban and Regional Planning", "URP"),

    # Science
    ("Mathematics", "MAT"),
    ("Applied Mathematics", "AMATH"),
    ("Physics", "PHY"),
    ("Applied Physics", "APHY"),
    ("Chemistry", "CHE"),
    ("Applied Chemistry", "ACHEM"),
    ("Biology", "BIO"),
    ("Biochemistry", "BIOC"),
    ("Microbiology", "MIC"),
    ("Biotechnology", "BIOTECH"),
    ("Molecular Biology", "MOLBIO"),
    ("Botany", "BOT"),
    ("Zoology", "ZOO"),
    ("Genetic Engineering and Biotechnology", "GEB"),
    ("Environmental Science", "ENVSCI"),
    ("Earth Science", "EARTH"),
    ("Geology", "GEOLOGY"),
    ("Geography", "GEO"),
    ("Geophysics", "GEOPHY"),
    ("Geochemistry", "GEOCHEM"),
    ("Astronomy", "ASTRO"),
    ("Astrophysics", "ASTROPHY"),
    ("Oceanography", "OCEAN"),
    ("Marine Science", "MARSCI"),
    ("Meteorology", "MET"),
    ("Nanotechnology", "NANO"),
    ("Neuroscience", "NEURO"),
    ("Material Science", "MATSCI"),

    # Business
    ("Accounting", "ACC"),
    ("Accounting and Information Systems", "AIS"),
    ("Accounting and Finance", "AF"),
    ("Finance", "FIN"),
    ("Finance and Banking", "FB"),
    ("Banking and Insurance", "BI"),
    ("Business Administration", "BBA"),
    ("Business Studies", "BUS"),
    ("Business Analytics", "BA"),
    ("Commerce", "COM"),
    ("Management", "MGT"),
    ("Marketing", "MKT"),
    ("Marketing Management", "MM"),
    ("Human Resource Management", "HRM"),
    ("Supply Chain Management", "SCM"),
    ("International Business", "IB"),
    ("International Management", "IM"),
    ("Entrepreneurship", "ENT"),
    ("Operations Management", "OM"),
    ("Project Management", "PM"),
    ("Risk Management", "RM"),
    ("Strategic Management", "SM"),
    ("Organizational Behavior", "OB"),
    ("Hospitality Management", "HM"),
    ("Hotel Management", "HOTEL"),
    ("Tourism Management", "TM"),
    ("Event Management", "EVENT"),
    ("Retail Management", "RETAIL"),
    ("Office Management", "OFFICE"),
    ("Real Estate Management", "REM"),

    # Economics & Social Science
    ("Economics", "ECO"),
    ("Applied Economics", "AECO"),
    ("Econometrics", "ECONOMET"),
    ("Development Economics", "DECO"),
    ("Financial Economics", "FECO"),
    ("International Economics", "IECO"),
    ("Political Economy", "PE"),
    ("Sociology", "SOC"),
    ("Social Work", "SW"),
    ("Political Science", "POL"),
    ("Public Administration", "PAD"),
    ("Public Administration and Governance", "PAG"),
    ("Public Policy", "PP"),
    ("Public Finance", "PF"),
    ("Public Health", "PH"),
    ("Anthropology", "ANT"),
    ("Archaeology", "ARC"),
    ("Criminology", "CRM"),
    ("Development Studies", "DS"),
    ("Disaster Management", "DM"),
    ("Peace and Conflict Studies", "PCS"),
    ("International Relations", "IR"),
    ("Gender Studies", "GEND"),
    ("Women Studies", "WOM"),
    ("Population Studies", "POP"),
    ("Demography", "DEMO"),
    ("Governance Studies", "GOV"),
    ("Security Studies", "SEC"),
    ("Migration Studies", "MIG"),
    ("Social Policy", "SP"),

    # Humanities & Languages
    ("Bangla", "BAN"),
    ("Bengali Language and Literature", "BLL"),
    ("English", "ENG"),
    ("English Language and Literature", "ELL"),
    ("History", "HIS"),
    ("Philosophy", "PHI"),
    ("Arabic", "ARB"),
    ("Arabic Language and Literature", "ALL"),
    ("Persian", "PER"),
    ("Persian Language and Literature", "PLL"),
    ("Sanskrit", "SAN"),
    ("Urdu", "URD"),
    ("Linguistics", "LING"),
    ("Applied Linguistics", "ALING"),
    ("Translation Studies", "TRANSST"),
    ("Comparative Literature", "CL"),
    ("Cultural Studies", "CULT"),
    ("Religious Studies", "REL"),
    ("Comparative Religion", "CREL"),
    ("Islamic Studies", "ISL"),
    ("Islamic History and Culture", "IHC"),
    ("Islamic Theology", "THEO"),
    ("Islamic Law", "ILAW"),
    ("Quranic Studies", "QURAN"),
    ("Hadith Studies", "HADITH"),
    ("Classical Studies", "CLASS"),
    ("Art History", "ARTH"),

    # Law
    ("Law", "LAW"),
    ("Constitutional Law", "CLAW"),
    ("Criminal Law", "CRLAW"),
    ("Corporate Law", "CORPLAW"),
    ("Commercial Law", "COMLAW"),
    ("International Law", "INTLAW"),
    ("Human Rights Law", "HRLAW"),
    ("Environmental Law", "ENLAW"),
    ("Intellectual Property Law", "IPLAW"),
    ("Tax Law", "TAXLAW"),
    ("Family Law", "FAMLAW"),
    ("Labour Law", "LABLAW"),
    ("Business Law", "BUSLAW"),
    ("Cyber Law", "CYBERLAW"),
    ("Public International Law", "PIL"),
    ("Private International Law", "PRIL"),

    # Medical
    ("Medical Science", "MED"),
    ("Medicine", "MEDICINE"),
    ("Clinical Medicine", "CLMED"),
    ("Internal Medicine", "IMED"),
    ("Surgery", "SUR"),
    ("Paediatrics", "PED"),
    ("Obstetrics and Gynaecology", "OBG"),
    ("Cardiology", "CARD"),
    ("Neurology", "NEU"),
    ("Nephrology", "NEPH"),
    ("Dermatology", "DERM"),
    ("Psychiatry", "PSYCH"),
    ("Orthopaedics", "ORTHO"),
    ("Ophthalmology", "OPH"),
    ("ENT", "ENT"),
    ("Radiology", "RAD"),
    ("Radiology and Imaging", "RADIMG"),
    ("Anesthesiology", "ANES"),
    ("Pathology", "PATH"),
    ("Community Medicine", "CM"),
    ("Anatomy", "ANA"),
    ("Physiology", "PHYS"),
    ("Pharmacology", "PHARM"),
    ("Forensic Medicine", "FM"),
    ("Oncology", "ONCO"),
    ("Hematology", "HEMA"),
    ("Endocrinology", "ENDO"),
    ("Gastroenterology", "GASTRO"),
    ("Pulmonology", "PUL"),
    ("Rheumatology", "RHEU"),
    ("Urology", "URO"),
    ("Neurosurgery", "NSURG"),
    ("Plastic Surgery", "PLAST"),
    ("Emergency Medicine", "EMED"),
    ("Family Medicine", "FMED"),
    ("Nuclear Medicine", "NUCMED"),
    ("Infectious Diseases", "IDIS"),
    ("Medical Genetics", "MGEN"),
    ("Epidemiology", "EPI"),

    # Dentistry & Health
    ("Dentistry", "DEN"),
    ("Dentistry and Oral Surgery", "DOS"),
    ("Dental Technology", "DTECH"),
    ("Dental Hygiene", "DH"),
    ("Nursing", "NUR"),
    ("General Nursing", "GN"),
    ("Midwifery", "MID"),
    ("Pharmacy", "PHA"),
    ("Physiotherapy", "PT"),
    ("Occupational Therapy", "OT"),
    ("Optometry", "OPT"),
    ("Audiology", "AUD"),
    ("Speech and Language Therapy", "SLT"),
    ("Respiratory Therapy", "RT"),
    ("Medical Laboratory Science", "MLS"),
    ("Clinical Laboratory Science", "CLS"),
    ("Medical Laboratory Technology", "MLT"),
    ("Medical Imaging Technology", "MIT"),
    ("Medical Radiography", "MRAD"),
    ("Medical Technology", "MEDTECH"),
    ("Health Information Management", "HIM"),
    ("Healthcare Management", "HCM"),
    ("Public Health and Epidemiology", "PHEPI"),
    ("Nutritional Science", "NUT"),
    ("Nutrition and Dietetics", "ND"),

    # Agriculture & Veterinary
    ("Agriculture", "AGR"),
    ("Agricultural Science", "AGSCI"),
    ("Agricultural Economics", "AGE"),
    ("Agricultural Extension", "EXT"),
    ("Agricultural Marketing", "AGM"),
    ("Agricultural Finance", "AGF"),
    ("Agricultural Statistics", "AGS"),
    ("Agronomy", "AGRON"),
    ("Horticulture", "HOR"),
    ("Soil Science", "SOIL"),
    ("Plant Pathology", "PP"),
    ("Plant Breeding", "PB"),
    ("Plant Genetics", "PG"),
    ("Crop Science", "CROP"),
    ("Crop Production", "CP"),
    ("Seed Science and Technology", "SST"),
    ("Entomology", "ENTM"),
    ("Fisheries", "FIS"),
    ("Animal Science", "ANS"),
    ("Animal Husbandry", "AH"),
    ("Animal Nutrition", "ANUT"),
    ("Dairy Science", "DAIRY"),
    ("Veterinary Science", "VET"),
    ("Veterinary Medicine", "VMED"),
    ("Veterinary Surgery", "VS"),
    ("Veterinary Pathology", "VP"),
    ("Veterinary Pharmacology", "VPHA"),
    ("Veterinary Public Health", "VPH"),
    ("Food Science and Technology", "FST"),
    ("Food Technology", "FT"),

    # Textile & Garments
    ("Textile Engineering", "TE"),
    ("Textile Technology", "TT"),
    ("Textile Chemistry", "TC"),
    ("Textile Wet Processing", "TWP"),
    ("Textile Testing", "TTEST"),
    ("Yarn Manufacturing", "YARN"),
    ("Fabric Manufacturing", "FAB"),
    ("Apparel Engineering", "APPENG"),
    ("Apparel Manufacturing", "AM"),
    ("Apparel Merchandising", "MERCH"),
    ("Fashion Design", "FD"),
    ("Fashion Technology", "FT"),
    ("Fashion Merchandising", "FM"),
    ("Garments Technology", "GT"),
    ("Garments Production", "GP"),
    ("Garments Design and Pattern Making", "GDPM"),
    ("Textile Engineering and Management", "TEM"),

    # Arts, Media & Creative
    ("Fine Arts", "FA"),
    ("Music", "MUS"),
    ("Theatre and Performance Studies", "TPS"),
    ("Graphic Design", "GRAPH"),
    ("Industrial Design", "INDDES"),
    ("Interior Design", "ID"),
    ("Product Design", "PD"),
    ("Photography", "PHOTO"),
    ("Animation", "ANIM"),
    ("Film and Television", "FTV"),
    ("Film Studies", "FILM"),
    ("Journalism and Media Studies", "JMS"),
    ("Mass Communication", "MC"),
    ("Communication Studies", "COMMST"),
    ("Media Studies", "MEDIA"),
    ("Digital Media", "DMEDIA"),
    ("Broadcast Journalism", "BJ"),
    ("Print Journalism", "PJ"),
    ("Advertising", "ADV"),
    ("Public Relations", "PR"),

    # Architecture & Planning
    ("Architecture", "ARCH"),
    ("Landscape Architecture", "LA"),
    ("Urban Design", "UD"),
    ("Regional Planning", "RP"),
    ("City Planning", "CITY"),
    ("Environmental Design", "EDES"),
    ("Construction Management", "CMGT"),

    # Library & Information
    ("Library and Information Science", "LIS"),
    ("Library Management", "LM"),
    ("Information Management", "IM"),
    ("Knowledge Management", "KM"),
    ("Archives and Records Management", "ARM"),
    ("Digital Library", "DL"),
    ("Documentation Science", "DOC"),
    ("Museum Studies", "MUSEUM"),

    # Tourism & Aviation
    ("Tourism and Hospitality Management", "THM"),
    ("Tourism Management", "TM"),
    ("Travel Management", "TRAVEL"),
    ("Hospitality and Tourism", "HT"),
    ("Culinary Arts", "CUL"),
    ("Food and Beverage Management", "FBM"),
    ("Airline Management", "AIR"),
    ("Aviation Management", "AVM"),

    # Environment
    ("Environmental Management", "ENVM"),
    ("Environmental Economics", "ENVECO"),
    ("Environmental Health", "ENVH"),
    ("Climate Science", "CLIMATE"),
    ("Climate Change Studies", "CCS"),
    ("Conservation Biology", "CONBIO"),
    ("Wildlife Management", "WLM"),
    ("Natural Resource Management", "NRM"),
    ("Disaster Risk Management", "DRM"),
    ("Water Management", "WM"),
    ("Water and Sanitation", "WASH"),

    # Sports
    ("Physical Education", "PE"),
    ("Sports Science", "SS"),
    ("Sports Management", "SM"),
    ("Exercise Science", "EXS"),
    ("Kinesiology", "KIN"),
    ("Sports Medicine and Rehabilitation", "SMR"),

    # Technical / Polytechnic
    ("Technical Education", "TECH"),
    ("Electrical Technology", "ET"),
    ("Mechanical Technology", "MT"),
    ("Civil Technology", "CT"),
    ("Computer Technology", "CPT"),
    ("Electronics Technology", "ELT"),
    ("Automobile Technology", "AT"),
    ("Power Technology", "PTG"),
    ("Architecture Technology", "ATC"),
    ("Refrigeration and Air Conditioning", "RAC"),
]


class Command(BaseCommand):
    help = "Seed global Deepafy departments."

    def handle(self, *args, **options):
        created = 0
        skipped = 0

        for name, code in DEPARTMENTS:
            existing = Department.objects.filter(name__iexact=name).first()

            if existing:
                skipped += 1
                continue

            Department.objects.create(
                name=name,
                code=code,
                is_active=True,
            )
            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Created: {created} | "
                f"Skipped existing: {skipped} | "
                f"Total: {Department.objects.count()}"
            )
        )
