# Generated by Django 6.1 on 2026-08-11 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('restricted', 'Restricted'), ('locked', 'Locked'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], default='draft', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
