# Generated by Django 6.1 on 2026-08-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('personal', 'Personal Account'), ('professional', 'Professional Account'), ('company', 'Company Account')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='identity.useridentity')),
            ],
            options={
                'ordering': ['account_type'],
                'constraints': [models.UniqueConstraint(fields=('identity', 'account_type'), name='unique_account_type_per_identity')],
            },
        ),
    ]
