# Generated by Django 6.1 on 2026-08-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0009_remove_category_unique_category_name_per_parent_and_more'),
        ('identity', '0003_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('personal_account', 'name'), name='unique_personal_hobby')],
            },
        ),
        migrations.CreateModel(
            name='PersonalInterestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_interested_categories', to='category_engine.category')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_categories', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['category__name'],
                'constraints': [models.UniqueConstraint(fields=('personal_account', 'category'), name='unique_personal_interested_category')],
            },
        ),
    ]
