# Generated by Django 6.1 on 2026-08-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_personalhobby_personalinterestedcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('professional_summary', models.TextField(blank=True)),
                ('focus_job_area', models.TextField(blank=True)),
                ('future_goal', models.TextField(blank=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('tab_colors', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_account', to='identity.useridentity')),
            ],
        ),
    ]
