# Generated by Django 6.1 on 2026-08-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_professionalaccount'),
        ('organization', '0007_countrydepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='permanent_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='permanent_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_permanent_addresses', to='organization.country'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='permanent_full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='present_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='present_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='present_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_present_addresses', to='organization.country'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='present_full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
