# Generated by Django 6.1 on 2026-08-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_hobby_alter_personalhobby_options_and_more'),
        ('organization', '0007_countrydepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_backgrounds', to='organization.country')),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_backgrounds', to='identity.professionalaccount')),
            ],
            options={
                'ordering': ['display_order', '-start_date', 'qualification'],
            },
        ),
    ]
