# Generated by Django 6.1 on 2026-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_skill_professionalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
