# Generated by Django 6.1 on 2026-08-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='mother_tongue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_tongue_users', to='identity.language'),
        ),
    ]
