# Generated by Django 6.1 on 2026-08-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_personalaccount_mother_tongue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], default='conversational', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_language_users', to='identity.language')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['language__name'],
                'constraints': [models.UniqueConstraint(fields=('personal_account', 'language'), name='unique_personal_language')],
            },
        ),
    ]
