# Generated by Django 6.1 on 2026-08-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_personallanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personallanguage',
            old_name='proficiency_level',
            new_name='proficiency',
        ),
        migrations.AlterField(
            model_name='personallanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_languages', to='identity.language'),
        ),
    ]
