# Generated by Django 6.1 on 2026-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_rename_proficiency_level_personallanguage_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useridentity',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
