# Generated by Django 6.1 on 2026-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_useridentity_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='password',
            field=models.CharField(default='!', max_length=128),
        ),
    ]
