# Generated by Django 6.1 on 2026-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
