# Generated by Django 6.1 on 2026-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
