# Generated by Django 6.1 on 2026-08-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_useridentity_first_name_useridentity_last_name'),
        ('organization', '0009_country_phone_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicbackground',
            options={'ordering': ['display_order', '-start_year', 'institution_name']},
        ),
        migrations.RenameField(
            model_name='academicbackground',
            old_name='qualification',
            new_name='degree_certificate',
        ),
        migrations.RenameField(
            model_name='academicbackground',
            old_name='institution',
            new_name='institution_name',
        ),
        migrations.RenameField(
            model_name='academicbackground',
            old_name='is_current',
            new_name='is_currently_studying',
        ),
        migrations.RemoveField(
            model_name='academicbackground',
            name='city',
        ),
        migrations.RemoveField(
            model_name='academicbackground',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicbackground',
            name='professional_account',
        ),
        migrations.RemoveField(
            model_name='academicbackground',
            name='start_date',
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='academic_certificates/'),
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='education_level',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='institution_type',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_backgrounds', to='identity.personalaccount'),
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='result_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='start_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicbackground',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('connections', 'Connections'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicbackground',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_academic_backgrounds', to='organization.country'),
        ),
    ]
