# Generated by Django 6.1 on 2026-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0022_personalaccount_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_backgrounds/'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='tab_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='professionalaccount',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='professional_backgrounds/'),
        ),
    ]
