# Generated by Django 6.1 on 2026-08-27 06:52

from django.db import migrations, models


def copy_hobby_names(
    apps,
    schema_editor,
):

    PersonalHobby = apps.get_model(
        "identity",
        "PersonalHobby",
    )


    for personal_hobby in PersonalHobby.objects.all():

        if personal_hobby.hobby_id:

            personal_hobby.name = (
                personal_hobby.hobby.name
            )

            personal_hobby.save(
                update_fields=[
                    "name",
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "identity",
            "0023_personalaccount_background_color_and_more",
        ),
    ]


    operations = [

        migrations.AlterModelOptions(
            name="personalhobby",
            options={
                "ordering": [
                    "created_at",
                ],
            },
        ),


        migrations.RemoveConstraint(
            model_name="personalhobby",
            name="unique_personal_hobby",
        ),


        migrations.AddField(
            model_name="personalhobby",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
            ),
        ),


        migrations.RunPython(
            copy_hobby_names,
            migrations.RunPython.noop,
        ),


        migrations.AddConstraint(
            model_name="personalhobby",
            constraint=models.UniqueConstraint(
                fields=(
                    "personal_account",
                    "name",
                ),
                name="unique_personal_hobby_name",
            ),
        ),


        migrations.RemoveField(
            model_name="personalhobby",
            name="hobby",
        ),

    ]