# Generated by Django 6.1 on 2026-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0024_alter_personalhobby_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
