# Generated by Django 6.1 on 2026-08-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0025_useridentity_is_staff_useridentity_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_experiences', to='identity.personalaccount'),
        ),
    ]
