# Generated by Django 6.1 on 2026-08-30 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0026_jobexperience_personal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='professional_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_experiences', to='identity.professionalaccount'),
        ),
    ]
