# Generated by Django 6.1 on 2026-08-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0027_alter_jobexperience_professional_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_responsibilities', to='identity.professionalaccount')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
