# Generated by Django 6.1 on 2026-08-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0028_professionalresponsibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionalResponsibility',
        ),
        migrations.DeleteModel(
            name='ProfessionalSkill',
        ),
    ]