# Generated by Django 6.1 on 2026-09-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0030_personalresponsibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='identity.personalaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact_type', 'normalized_value'), name='unique_personal_contact_value'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('personal_account', 'contact_type'), name='unique_primary_contact_per_type')],
            },
        ),
    ]
