# Generated by Django 6.1 on 2026-09-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0031_personalcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHighestAcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_as_highest', to='identity.academicbackground')),
                ('personal_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highest_academic_selection', to='identity.personalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRunningProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_running_professions', to='identity.jobexperience')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_professions', to='identity.personalaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('personal_account', 'job_experience'), name='unique_personal_running_profession')],
            },
        ),
    ]
