# Generated by Django 6.1 on 2026-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0036_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal Account'), ('professional', 'Professional Account'), ('company', 'Company Account'), ('institution', 'Institution Account')], max_length=30),
        ),
    ]
