# Generated by Django 6.1 on 2026-08-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
