# Generated by Django 6.1 on 2026-08-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0003_categorytranslation'),
        ('organization', '0007_countrydepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCountryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_overrides', to='category_engine.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_overrides', to='organization.country')),
            ],
            options={
                'ordering': ['display_order', 'category'],
                'constraints': [models.UniqueConstraint(fields=('category', 'country'), name='unique_category_country_override')],
            },
        ),
    ]
