# Generated by Django 6.1 on 2026-08-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0004_categorycountryoverride'),
        ('organization', '0007_countrydepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_configuration', models.JSONField(default=dict)),
                ('current_configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='category_engine.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_versions', to='organization.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
