# Generated by Django 6.1 on 2026-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0005_categoryversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden'), ('disabled', 'Disabled')], default='public', max_length=20),
        ),
    ]
