# Generated by Django 6.1 on 2026-08-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0006_remove_category_is_active_category_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
