# Generated by Django 6.1 on 2026-08-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0007_category_deleted_at_category_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='category_engine.category')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='category_engine.category')),
            ],
            options={
                'ordering': ['display_order', 'child'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='unique_category_relationship')],
            },
        ),
    ]
