# Generated by Django 6.1 on 2026-08-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_engine', '0008_categoryrelationship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_slug_per_parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
