from django.urls import path

from .views import (
    institution_type_list,
    institution_authority_list,
    institution_profile_by_username,
    institution_appearance_update,
    institution_profile_update,
    institution_academic_data,
    institution_academic_summary,
    institution_academic_overview,
    institution_academic_levels_public,
    institution_academic_levels,
    institution_academic_level_delete,
    institution_staff_services,
    institution_unclaimed_staff,
    institution_subjects,
    institution_subject_detail,
    institution_departments,
    institution_department_detail,
    institution_academic_sessions,
    institution_academic_session_detail,
)


urlpatterns = [
    path(
        "profile/username/<str:username>/",
        institution_profile_by_username,
        name="institution-profile-by-username",
    ),
    path(
        "profile/appearance/",
        institution_appearance_update,
        name="institution-appearance-update",
    ),
    path(
        "profile/update/",
        institution_profile_update,
        name="institution-profile-update",
    ),
    path(
        "types/",
        institution_type_list,
        name="institution-type-list",
    ),
    path(
        "authorities/",
        institution_authority_list,
        name="institution-authority-list",
    ),
    path(
        "academic/levels/",
        institution_academic_levels,
        name="institution-academic-levels",
    ),
    path(
        "profile/username/<str:username>/academic-levels/",
        institution_academic_levels_public,
        name="institution-academic-levels-public",
    ),
    path(
        "academic/levels/<int:level_id>/",
        institution_academic_level_delete,
        name="institution-academic-level-delete",
    ),
    path(
        "academic/",
        institution_academic_data,
        name="institution-academic-data",
    ),
    path(
        "sessions/",
        institution_academic_sessions,
        name="institution-academic-sessions",
    ),
    path(
        "sessions/<int:session_id>/",
        institution_academic_session_detail,
        name="institution-academic-session-detail",
    ),
    path(
        "subjects/",
        institution_subjects,
        name="institution-subjects",
    ),
    path(
        "subjects/<int:subject_id>/",
        institution_subject_detail,
        name="institution-subject-detail",
    ),
    path(
        "departments/",
        institution_departments,
        name="institution-departments",
    ),
    path(
        "departments/<int:department_id>/",
        institution_department_detail,
        name="institution-department-detail",
    ),
    path(
        "staff/",
        institution_staff_services,
        name="institution-staff-services",
    ),
    path(
        "staff/manual/",
        institution_unclaimed_staff,
        name="institution-unclaimed-staff",
    ),
    path(
        "profile/username/<str:username>/academic-summary/",
        institution_academic_summary,
        name="institution-academic-summary",
    ),
    path(
        "profile/username/<str:username>/academic-overview/",
        institution_academic_overview,
        name="institution-academic-overview",
    ),
]
