# Generated by Django 6.1 on 2026-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('recent_needafy', 'Recent Needafy Posts'), ('recent_product_listings', 'Recent Product Listings'), ('top_manufacturers', 'Top Manufacturers'), ('recent_jobs', 'Recent Posted Jobs'), ('trending_products', 'Trending Products'), ('top_verified_suppliers', 'Top Verified Suppliers'), ('featured_brands', 'Featured Brands'), ('business_updates', 'Business Updates'), ('featured_services', 'Featured Services'), ('platform_statistics', 'Platform Statistics'), ('join_deepafy', 'Join Deepafy')], max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('show_view_all', models.BooleanField(default=True)),
                ('view_all_label', models.CharField(default='View All', max_length=100)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
