# Generated by Django 6.1 on 2026-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='desktop_position',
            field=models.CharField(default='center', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='mobile_position',
            field=models.CharField(default='center', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='object_fit',
            field=models.CharField(default='cover', max_length=20),
        ),
    ]
