# Generated by Django 6.1 on 2026-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepagecta_platformstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/heroes/'),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
