# Generated by Django 6.1 on 2026-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepagehero_media_file_alter_homepagehero_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='card_limit',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of items to display.'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='data_source',
            field=models.CharField(choices=[('products', 'Products'), ('needafy_posts', 'Needafy Posts'), ('organizations', 'Organizations'), ('services', 'Services'), ('jobs', 'Jobs'), ('opportunities', 'Opportunities'), ('custom', 'Custom')], default='custom', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='view_all_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(help_text='Unique section identifier.', max_length=100, unique=True),
        ),
    ]
