# Generated by Django 6.1 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_homepagesection_card_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStartedPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Join Deepafy', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Create your account and get started.')),
                ('left_heading', models.CharField(default='Your journey starts here.', max_length=255)),
                ('left_description', models.TextField(blank=True)),
                ('personal_title', models.CharField(default='Personal Account', max_length=255)),
                ('personal_description', models.TextField(blank=True)),
                ('company_title', models.CharField(default='Company Account', max_length=255)),
                ('company_description', models.TextField(blank=True)),
                ('login_text', models.CharField(default='Log in', max_length=100)),
                ('page_background_color', models.CharField(default='#F8FAFC', max_length=20)),
                ('left_panel_color', models.CharField(default='#0A66C2', max_length=20)),
                ('heading_color', models.CharField(default='#111827', max_length=20)),
                ('text_color', models.CharField(default='#6B7280', max_length=20)),
                ('personal_card_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('company_card_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('border_color', models.CharField(default='#E5E7EB', max_length=20)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('title_font_size', models.PositiveIntegerField(default=36)),
                ('subtitle_font_size', models.PositiveIntegerField(default=16)),
                ('heading_font_size', models.PositiveIntegerField(default=40)),
                ('body_font_size', models.PositiveIntegerField(default=16)),
                ('card_title_font_size', models.PositiveIntegerField(default=20)),
                ('card_text_font_size', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
