# Generated by Django 6.1 on 2026-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_getstartedpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='institution_card_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='institution_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='institution_title',
            field=models.CharField(default='Institution Account', max_length=255),
        ),
    ]
