# Generated by Django 6.1 on 2026-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_getstartedpagesettings_institution_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='company_icon',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/get_started/icons/'),
        ),
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='institution_icon',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/get_started/icons/'),
        ),
        migrations.AddField(
            model_name='getstartedpagesettings',
            name='personal_icon',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/get_started/icons/'),
        ),
    ]
