# Generated by Django 6.1 on 2026-09-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0033_socialmediaplatform_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('business', 'Business / Company'), ('education', 'Education')], max_length=30)),
                ('activity_type', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
