# Generated by Django 6.1 on 2026-09-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('identity', '0033_socialmediaplatform_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='activity.activity')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_likes', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'personal_account'), name='unique_activity_like')],
            },
        ),
    ]
