# Generated by Django 6.1 on 2026-09-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitylike'),
        ('identity', '0033_socialmediaplatform_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activity.activity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activity.activitycomment')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to='identity.personalaccount')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
