# Generated by Django 6.1 on 2026-09-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activitycomment'),
        ('identity', '0033_socialmediaplatform_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#F5F8FC', max_length=20)),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='activity_wallpapers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_appearance', to='identity.personalaccount')),
            ],
        ),
    ]
