# Generated by Django 6.1 on 2026-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activityappearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefaultAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#F5F8FC', max_length=20)),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='activity_default_wallpapers/')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
