# Generated by Django 6.1 on 2026-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activitydefaultappearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityappearance',
            name='background_color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
