# Generated by Django 6.1 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activityappearance_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefaultappearance',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
