# Generated by Django 6.1 on 2026-09-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activitydefaultappearance_singleton_key'),
        ('identity', '0037_alter_accounttype_account_type'),
        ('institution', '0004_institutionprofile_institution_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='institution.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='identity.personalaccount'),
        ),
    ]
