# Generated by Django 6.1 on 2026-09-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_institution_alter_activity_personal_account'),
        ('identity', '0037_alter_accounttype_account_type'),
        ('institution', '0004_institutionprofile_institution_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycomment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to='institution.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to='identity.personalaccount'),
        ),
    ]
