# Generated by Django 6.1 on 2026-08-12 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_mobile_number', models.CharField(max_length=30)),
                ('registered_address', models.TextField()),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
