# Generated by Django 6.1 on 2026-08-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_personalaccount'),
        ('organization', '0003_administrativerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_assignments', to='identity.useridentity')),
                ('reporting_boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_administrative_assignments', to='identity.useridentity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.administrativerole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
