# Generated by Django 6.1 on 2026-09-22 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_country_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='countries/flags/'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LocationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_levels', to='organization.country')),
            ],
            options={
                'ordering': ['country', 'level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_locations', to='organization.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.administrativelocation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.locationlevel')),
            ],
            options={
                'ordering': ['country', 'level', 'sort_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='locationlevel',
            constraint=models.UniqueConstraint(fields=('country', 'level'), name='unique_location_level_per_country'),
        ),
        migrations.AddConstraint(
            model_name='administrativelocation',
            constraint=models.UniqueConstraint(fields=('level', 'parent', 'name'), name='unique_location_name_per_parent'),
        ),
    ]
