# Generated by Django 6.1 on 2026-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_country_flag_country_flag_emoji_country_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='region',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
