# Generated by Django 6.1 on 2026-09-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('organization', '0011_alter_region_options_region_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('full_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='institution_covers/')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='institution_backgrounds/')),
                ('tab_colors', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrative_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institution_profiles', to='organization.administrativelocation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_profiles', to='organization.country')),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='institution.institutiontype')),
            ],
        ),
    ]
