# Generated by Django 6.1 on 2026-09-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institutionprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionprofile',
            name='username',
        ),
    ]
