# Generated by Django 6.1 on 2026-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_remove_institutionprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='institution_types',
            field=models.ManyToManyField(blank=True, related_name='institution_profiles', to='institution.institutiontype'),
        ),
    ]
