# Generated by Django 6.1 on 2026-09-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institutionprofile_institution_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='affiliation_board',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='eiin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='management_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('non_government', 'Non-Government')], max_length=30),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='mpo_status',
            field=models.CharField(blank=True, choices=[('mpo', 'MPO'), ('non_mpo', 'Non-MPO'), ('not_applicable', 'Not Applicable')], max_length=30),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_teachers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
