# Generated by Django 6.1 on 2026-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_institutionprofile_map_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution_featured/'),
        ),
    ]
