# Generated by Django 6.1 on 2026-09-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_institutionprofile_featured_image'),
        ('organization', '0011_alter_region_options_region_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('relationship_type', models.CharField(choices=[('education_board', 'Education Board'), ('academic_affiliation', 'Academic Affiliation'), ('regulatory_authority', 'Regulatory Authority'), ('governing_authority', 'Governing Authority')], max_length=40)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_authorities', to='organization.country')),
                ('institution_types', models.ManyToManyField(blank=True, related_name='authorities', to='institution.institutiontype')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='institution_profiles', to='institution.institutionauthority'),
        ),
        migrations.AddConstraint(
            model_name='institutionauthority',
            constraint=models.UniqueConstraint(fields=('country', 'name', 'relationship_type'), name='unique_country_authority_relationship'),
        ),
    ]
