# Generated by Django 6.1 on 2026-09-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institutionauthority_institutionprofile_affiliations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAcademicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(help_text='Students, Teachers, Staff, Class 1, Class 2, etc.', max_length=100)),
                ('total', models.PositiveIntegerField(default=0)),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('present', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_data', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['-date', 'category'],
                'indexes': [models.Index(fields=['institution', 'date'], name='academic_institution_date_idx'), models.Index(fields=['institution', 'category'], name='academic_inst_cat_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'date', 'category'), name='unique_institution_academic_date_category')],
            },
        ),
    ]
