# Generated by Django 6.1 on 2026-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_institutionacademicdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionacademicdata',
            name='leave',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
