# Generated by Django 6.1 on 2026-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institutionacademicdata_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionacademicdata',
            name='female_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionacademicdata',
            name='female_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionacademicdata',
            name='male_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionacademicdata',
            name='male_present',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
