# Generated by Django 6.1 on 2026-09-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_institutionacademicdata_female_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(default='Class', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['created_at', 'name'],
                'indexes': [models.Index(fields=['institution', 'level_type'], name='academic_level_inst_type_idx'), models.Index(fields=['institution', 'name'], name='academic_level_inst_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'level_type', 'name', 'parent'), name='unique_institution_academic_level')],
            },
        ),
    ]
