# Generated by Django 6.1 on 2026-09-28 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_institutionacademiclevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField()),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('passing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('FORMER', 'Former Staff'), ('RETIRED', 'Retired Alumni'), ('IN_MEMORY', 'In Memory')], default='RUNNING', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_staff_services', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['-joining_date', 'identity_id'],
                'indexes': [models.Index(fields=['institution', 'status'], name='inst_staff_status_idx'), models.Index(fields=['identity', 'status'], name='identity_staff_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'identity'), name='unique_institution_staff_identity')],
            },
        ),
    ]
