# Generated by Django 6.1 on 2026-09-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0014_subject_institutionstaffservice_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnclaimedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='institution_staff/unclaimed/')),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField()),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('passing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('FORMER', 'Former Staff'), ('RETIRED', 'Retired Alumni'), ('IN_MEMORY', 'In Memory')], default='RUNNING', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unclaimed_people', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['-joining_date', 'full_name'],
                'indexes': [models.Index(fields=['institution', 'status'], name='unclaimed_status_idx'), models.Index(fields=['institution', 'full_name'], name='unclaimed_name_idx')],
            },
        ),
    ]
