# Generated by Django 6.1 on 2026-09-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0016_unclaimedpersonqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='UPCOMING', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['institution', 'status'], name='acad_sess_inst_status_idx'), models.Index(fields=['institution', 'is_current'], name='acad_sess_inst_current_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_institution_academic_session')],
            },
        ),
    ]
