# Generated by Django 6.1 on 2026-10-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0017_institutionacademicsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_by_institution',
        ),
    ]
