# Generated by Django 6.1 on 2026-10-01 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='global_identity_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Global Identity Code must be 3 to 8 English letters or numbers.', regex='^[A-Za-z0-9]{3,8}$')]),
        ),
    ]
