# Generated by Django 6.1 on 2026-10-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_institutionprofile_global_identity_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_student_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('guardian_mobile', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('roll', models.CharField(blank=True, max_length=100)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('previous_institution', models.CharField(blank=True, max_length=255)),
                ('admission_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('DROPPED', 'Dropped')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='institution.institutionacademicsession')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='institution.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='institution.institutionprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='institution.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'institution', 'academic_session'), name='unique_student_institution_session')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(upload_to='student_profile_photos/')),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photos', to='institution.student')),
            ],
            options={
                'ordering': ['-academic_year', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_photo_academic_year')],
            },
        ),
    ]
