# Generated by Django 6.1 on 2026-10-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_student_studentenrollment_studentprofilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_id_sequence', to='institution.institutionprofile')),
            ],
        ),
    ]
