# Generated by Django 6.1 on 2026-10-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_studentidsequence'),
        ('organization', '0011_alter_region_options_region_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='permanent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_permanent', to='organization.administrativelocation'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_present', to='organization.administrativelocation'),
        ),
    ]
