# Generated by Django 6.1 on 2026-10-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_student_permanent_location_student_present_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInstitutionIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_student_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_identities', to='institution.institutionprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_identities', to='institution.student')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'global_student_id'), name='unique_student_id_per_institution'), models.UniqueConstraint(fields=('student', 'institution'), name='unique_student_institution_identity')],
            },
        ),
    ]
