# Generated by Django 6.1 on 2026-10-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0025_institutionattendancesettings_institutionholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentAcademicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_values', to='institution.institutionacademiclevel')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_values', to='institution.studentenrollment')),
            ],
            options={
                'ordering': ['academic_level__created_at', 'academic_level__name'],
                'indexes': [models.Index(fields=['enrollment', 'academic_level'], name='enrollment_academic_level_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'academic_level'), name='unique_enrollment_academic_level_value')],
            },
        ),
    ]
