# Generated by Django 6.1 on 2026-10-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0026_studentenrollmentacademicvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='previous_institution_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='previous_institution_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_student_enrollments', to='institution.institutionprofile'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='previous_institution_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('MANUAL', 'Manual'), ('DEEPAFY', 'Deepafy Institution')], default='N/A', max_length=20),
        ),
    ]
