# Generated by Django 6.1 on 2026-10-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0027_studentenrollment_previous_institution_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAdmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_types', to='institution.institutionprofile')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='admission_type_inst_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_institution_admission_type')],
            },
        ),
    ]
