# Generated by Django 6.1 on 2026-10-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0030_holiday_date_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='institution.institutionstaffservice')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['staff_service', 'date'], name='institution_staff_s_5584e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff_service', 'date'), name='unique_staff_attendance_date')],
            },
        ),
    ]
