# Generated by Django 6.1 on 2026-10-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0031_institutionstaffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionstaffattendance',
            name='unclaimed_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='institution.unclaimedperson'),
        ),
        migrations.AlterField(
            model_name='institutionstaffattendance',
            name='staff_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='institution.institutionstaffservice'),
        ),
        migrations.AddConstraint(
            model_name='institutionstaffattendance',
            constraint=models.UniqueConstraint(fields=('unclaimed_person', 'date'), name='unique_manual_staff_attendance_date'),
        ),
    ]
