from django.urls import path

from . import views


urlpatterns = [
    path(
        "signup/",
        views.signup,
        name="signup",
    ),
    path(
        "login/",
        views.login,
        name="login",
    ),
    path(
        "forgot-password/",
        views.forgot_password,
        name="forgot-password",
    ),
    path(
        "verify-otp/",
        views.verify_otp,
        name="verify-otp",
    ),
    path(
        "reset-password/",
        views.reset_password,
        name="reset-password",
    ),
    path(
        "",
        views.identity_list,
        name="identity-list",
    ),
    path(
        "create/",
        views.identity_create,
        name="identity-create",
    ),
    path(
        "<int:identity_id>/",
        views.identity_detail,
        name="identity-detail",
    ),
    path(
        "<int:identity_id>/update/",
        views.identity_update,
        name="identity-update",
    ),
    path(
        "<int:identity_id>/delete/",
        views.identity_delete,
        name="identity-delete",
    ),
    path(
        "<int:identity_id>/account-types/",
        views.account_type_list,
        name="account-type-list",
    ),
    path(
        "account-types/create/",
        views.account_type_create,
        name="account-type-create",
    ),
    path(
        "personal-accounts/create/",
        views.personal_account_create,
        name="personal-account-create",
    ),
    path(
        "<int:identity_id>/personal-account/",
        views.personal_account_detail,
        name="personal-account-detail",
    ),
    path(
        "<int:identity_id>/personal-account/update/",
        views.personal_account_update,
        name="personal-account-update",
    ),
    path(
        "<int:identity_id>/personal-account/background-color/",
        views.personal_background_color_update,
        name="personal-background-color-update",
    ),
    path(
        "<int:identity_id>/personal-account/background-image/",
        views.personal_background_image_update,
        name="personal-background-image-update",    
    ),
    path(
        "<int:identity_id>/personal-account/tab-colors/",
        views.personal_tab_colors_update,
        name="personal-tab-colors-update",
    ),
    path(
        "<int:identity_id>/personal-account/photos/",
        views.personal_account_photos_update,
        name="personal-account-photos-update",
    ),

    # Professional Account
    path(
        "professional-accounts/create/",
        views.professional_account_create,
        name="professional-account-create",
    ),
    path(
        "<int:identity_id>/professional-account/",
        views.professional_account_detail,
        name="professional-account-detail",
    ),
    path(
        "<int:identity_id>/professional-account/update/",
        views.professional_account_update,
        name="professional-account-update",
    ),
    path(
        "<int:identity_id>/professional-account/background-image/",
        views.professional_background_image_update,
        name="professional-background-image-update",
    ),
    path(
        "<int:identity_id>/professional-account/tab-colors/",
        views.professional_tab_colors_update,
        name="professional-tab-colors-update",
    ),

    # Job Experience
    path(
        "job-experiences/create/",
        views.job_experience_create,
        name="job-experience-create",
    ),
    path(
        "<int:identity_id>/job-experiences/",
        views.job_experience_list,
        name="job-experience-list",
    ),
    path(
        "job-experiences/<int:experience_id>/",
        views.job_experience_detail,
        name="job-experience-detail",
    ),
    path(
        "job-experiences/<int:experience_id>/update/",
        views.job_experience_update,
        name="job-experience-update",
    ),
    path(
        "job-experiences/<int:experience_id>/delete/",
        views.job_experience_delete,
        name="job-experience-delete",
    ),
    path(
        "personal-accounts/<int:personal_account_id>/job-experiences/create/",
        views.personal_job_experience_create,
        name="personal-job-experience-create",
    ),
    path(
        "personal-accounts/<int:personal_account_id>/job-experiences/",
        views.personal_job_experience_list,
        name="personal-job-experience-list",
    ),
    path(
        "personal-accounts/<int:personal_account_id>/job-experiences/<int:experience_id>/update/",
        views.personal_job_experience_update,
        name="personal-job-experience-update",
    ),

    path(
        "personal-accounts/<int:personal_account_id>/job-experiences/<int:experience_id>/delete/",
        views.personal_job_experience_delete,
        name="personal-job-experience-delete",
    ),

        # Personal Responsibilities
    path(
        "personal-accounts/<int:personal_account_id>/responsibilities/create/",
        views.personal_responsibility_create,
        name="personal-responsibility-create",
    ),
    path(
        "personal-accounts/<int:personal_account_id>/responsibilities/",
        views.personal_responsibility_list,
        name="personal-responsibility-list",
    ),

    path(
        "personal-accounts/<int:personal_account_id>/responsibilities/<int:responsibility_id>/update/",
        views.personal_responsibility_update,
        name="personal-responsibility-update",
    ),
    path(
        "personal-accounts/<int:personal_account_id>/responsibilities/<int:responsibility_id>/delete/",
        views.personal_responsibility_delete,
        name="personal-responsibility-delete",
    ),


    # Skills
    path(
        "skills/create/",
        views.skill_create,
        name="skill-create",
    ),
    path(
        "skills/",
        views.skill_list,
        name="skill-list",
    ),

    # Academic Background
    path(
        "academic-backgrounds/create/",
        views.academic_background_create,
        name="academic-background-create",
    ),
    path(
        "<int:identity_id>/academic-backgrounds/",
        views.academic_background_list,
        name="academic-background-list",
    ),
    path(
        "academic-backgrounds/<int:academic_id>/",
        views.academic_background_detail,
        name="academic-background-detail",
    ),
    path(
        "academic-backgrounds/<int:academic_id>/update/",
        views.academic_background_update,
        name="academic-background-update",
    ),
    path(
        "academic-backgrounds/<int:academic_id>/delete/",
        views.academic_background_delete,
        name="academic-background-delete",
    ),

    # Languages
    path(
        "<int:personal_account_id>/languages/",
        views.languages,
        name="languages",
    ),
    path(
        "languages/<int:language_id>/",
        views.language_detail,
        name="language-detail",
    ),

    # Hobbies
    path(
        "hobbies/",
        views.hobby_list,
        name="hobby-list",
    ),
    path(
        "hobbies/create/",
        views.hobby_create,
        name="hobby-create",
    ),
    path(
        "hobbies/reorder/",
        views.hobby_reorder,
        name="hobby-reorder",
    ),
    path(
        "hobbies/<int:hobby_id>/update/",
        views.hobby_update,
        name="hobby-update",
    ), 
    path(
        "hobbies/<int:hobby_id>/delete/",
        views.hobby_delete,
        name="hobby-delete",
    ),
    # Personal Hobbies
    path(
        "<int:personal_account_id>/hobbies/",
        views.personal_hobby_list,
        name="personal-hobby-list",
    ),
    path(
        "<int:personal_account_id>/hobbies/add/",
        views.personal_hobby_add,
        name="personal-hobby-add",
    ),
    path(
        "<int:personal_account_id>/hobbies/<int:personal_hobby_id>/remove/",
        views.personal_hobby_remove,
        name="personal-hobby-remove",
    ),
      # Personal Interested Categories
    path(
        "<int:personal_account_id>/interested-categories/",
        views.personal_interested_category_list,
        name="personal-interested-category-list",
    ),
    path(
        "<int:personal_account_id>/interested-categories/add/",
        views.personal_interested_category_add,
        name="personal-interested-category-add",
    ),
    path(
        "<int:personal_account_id>/interested-categories/<int:category_id>/remove/",
        views.personal_interested_category_remove,
        name="personal-interested-category-remove",
    ),
]

